### ISSUE TITLE
Generating CRUD wrappers around existing models

### ISSUE THREAD

**Issue by Ludar-Pavel** [nafiesl/SimpleCrudGenerator#24]
As described. A possible usecase for the library is wrapping an already built model into a CRUD system - resolving this issue will imply that the library can do so.

**Comment by nafiesl** [comment]
Hi @Ludar-Pavel, ok got your point. You say we need to handle this. Instead of returning an error/warning, we want to generate the CRUD feature anyway (or asking confirmation to the user first).
 
![screenshot_2020-11-03_001](https://user-images.githubusercontent.com/8721551/97945041-49dc4c80-1dc1-11eb-8256-896db858926a.jpg)

Correct?

**Comment by Ludar-Pavel** [comment]
Yep. That's more of a feature request than a bug, though - the current behaviour seems to be intentional.

**Comment by nafiesl** [comment]
> the current behaviour seems to be intentional.

Yes correct @Ludar-Pavel.

**Comment by nafiesl** [comment]
hello @Ludar-Pavel could you please try again with dev-master version? 
```bash
$ composer require luthfi/simple-crud-generator dev-master --dev
```
Then try to generate the CRUD files from an existing model class.

![screenshot_2020-11-14_012](https://user-images.githubusercontent.com/8721551/99150156-8f581e00-26cd-11eb-87ec-3f7ccf4fe70f.jpg)

**Comment by nafiesl** [comment]
Resolved on https://github.com/nafiesl/SimpleCrudGenerator/releases/tag/1.5.0
