### ISSUE TITLE
Cannot install when running latest Laravel an php 8.0.14

### ISSUE THREAD

**Issue by rabol** [nafiesl/SimpleCrudGenerator#45]
composer require luthfi/simple-crud-generator:^2.0 

error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - luthfi/simple-crud-generator[2.0.0, ..., 2.4.1] require laravel/browser-kit-testing ^6.0 -> satisfiable by laravel/browser-kit-testing[v6.0.0, ..., 6.x-dev].
    - laravel/browser-kit-testing[v6.2.0, ..., 6.x-dev] require symfony/css-selector ^5.0 -> found symfony/css-selector[v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/browser-kit-testing[v6.0.0, ..., v6.1.0] require php ^7.2 -> your php version (8.0.14) does not satisfy that requirement.
    - Root composer.json requires luthfi/simple-crud-generator ^2.0 -> satisfiable by luthfi/simple-crud-generator[2.0.0, ..., 2.4.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nafiesl** [comment]
Hi, @rabol. Let me try to reproduce it.

**Comment by nafiesl** [comment]
I am getting the same error.

![screen_2021-12-26_002](https://user-images.githubusercontent.com/8721551/147409234-cdc3e48e-e9db-4e51-b45e-c2fe5cc03971.jpg)

This is caused by the `laravel/browser-kit-testing` package is still require `symfony/css-selector:^5.0`. Where the `symfony/css-selector:^5.0` package requires `php: >=7.2.5` (so can't install it on php 8.x).

Some possible solutions:

1. We are asking the laravel team to update the `laravel/browser-kit-testing` to support `symfony/css-selector:^5.0|^6.0`. Or
2. Install the laravel project using PHP version 7.4.*, add the `luthfi/simple-crud-generator` package, then switch to php 8.0 for development or production.

Any other suggestions are very welcome, @rabol.

Thanks.

**Comment by nafiesl** [comment]
@rabol I got another solution that works:

After install a new laravel project using php 8.0, downgrade the `symfony/css-selector` package by running:
```
$ composer require symfony/css-selector:^5.0
```
Then try to install the CRUD generator again:
```
$ composer require luthfi/simple-crud-generator:^2.0
```
See if it works for you as well.

Thanks.
